version: 2
jobs:
  build:
    docker:
      # use a wine image to successfully build a windows application
      # circle ci only supports mac and linux environments, so this is necessary
      - image: electronuserland/builder:wine-mono

    # set working directory
    working_directory: ~/repo
    
    # specify steps for build job
    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          # install yarn packages
          name: "Install Packages"
          command: yarn install

      - save_cache:
          # cache node modules for faster builds
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      
      # get version number from package json
      - run:
          name: "Get Project Version"
          command: echo export TAG=$(eval node -p "require\(\'./package.json\'\).version") >> $BASH_ENV
            
      - run:
          # build electron application
          # package.json forces this build to be a windows intaller
          name: "Build Application"
          command: yarn electron:build

      - store_artifacts:
          # store installer as an artifact to access via circle ci
          path: ./dist_electron/dot-deployer Setup ${TAG}.exe
      
      - persist_to_workspace:
          # persist installer to workspace so release job can access
          root: ./dist_electron
          paths: 
            - dot-deployer Setup ${TAG}.exe

  release:
    docker:
      # use docker go image to leverage ghr library
      - image: circleci/golang:1.8

    steps:
        # mount workspace from build job
      - attach_workspace:
          at: ./dist_electron

      - run:
          name: "Publish Installer on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Test Release Title" -b "Test Release Body" -soft ${TAG} "./dist_electron/dot-deployer Setup ${TAG}.exe"

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          # filters:
          #   branches:
          #     only:
          #       - master
          requires:
            - build
