version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!

      # run build!
      - run: yarn electron:build

  release:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.8

    dependencies:
      pre:
        - go get github.com/tcnksm/ghr

    steps:
      - run:
          name: "Publish Installer on GitHub"
          command: |
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Test Release Title" -b "Test Release Body" -delete "3.0.0" ./dist_electron/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
